# Define variables for data set files and scripts

DATA_DIR := datasets

# Check for files
# .PHONY: all


#help:
#	@echo "make help"
#	@echo "make all"
#	@echo "make clean"
#   @echo "make data"

# unzip file and remove zip file
unzip:
	unzip


#checkdatasets:
#	@echo "Checking for datasets..."
#	if(stat -c "%n %s" datasets/*.csv && stat -c "%n %s" datasets/*.json); then \
#		echo "Datasets found!"; \
#	else \
#		echo "Datasets not found!"; \
#		exit 1; \
#	fi

# convert_json_to_csv:
#	@echo "Converting json to csv..."
#	@python3 src/convert_json_to_csv.py


# run data preprocessing notebook
# how to run notebooks: jupyter nbconvert --to notebook --execute mynotebook.ipynb

# Generate graphs?


# clean:
#	@echo "Cleaning up..."